VERSION = "1.0.0 20250206.0811"
TITLE = "AI Vision OCDU %s" % VERSION
ABOUT = "Version %s \n-updates: \
    \n-Put choose model in menubar corner \
    \n-Add theme change \
    \n-Clear pixmap if image path not found in data table \
    \n-Add font config to drawing" % VERSION

STEP_READ_TRIGGER = "STEP_READ_TRIGGER"
STEP_PREPROCESS = "STEP_PREPROCESS"
STEP_ON_LIGHTING = "STEP_ON_LIGHTING"
STEP_OFF_LIGHTING = "STEP_OFF_LIGHTING"
STEP_VISION_DETECTION = "STEP_VISION_DETETION"
STEP_VISION_CHECKING_LED = "STEP_VISION_CHECKING_LED"
STEP_VISION_COMBINE = "STEP_VISION_COMBINE"
STEP_OUTPUT = "STEP_OUTPUT"
STEP_WRITE_LOG = "STEP_WRITE_LOG"
STEP_RELEASE = "STEP_RELEASE"

RESULT_WAIT = "WAIT"
RESULT_PASS = "PASS"
RESULT_FAIL = "FAIL"

ETIP_INDEX = 0
RUBBER_INDEX = 1
TAPE_INDEX = 2
DEFECT_INDEX = 3

ERROR_ETIP_1 = "ERROR_ETIP_1"
ERROR_ETIP_2 = "ERROR_ETIP_2"
ERROR_RUBBER_1 = "ERROR_RUBBER_1"
ERROR_RUBBER_2 = "ERROR_RUBBER_2"
ERROR_TAPE = "ERROR_TAPE"
ERROR_DEFECT = "ERROR_DEFECT"

CV_GREEN = (0, 255, 0)
CV_RED = (0, 0, 255)
CV_YELLOW = (0, 255, 255)
CV_ORANGE = (175, 0, 175)

FILENAME_FORMAT = "%Y%m%d_%H%M%S.jpg"
DATETIME_FORMAT = "%Y/%m/%d %H:%M:%S"
FOLDER_DATE_FORMAT = "%Y-%m-%d"

IMAGE_PATH_COLUMN = 4

FONT_CONFIG_PATH = "res/font/font.json"